module.exports.types = [
  "Business Cards",
  "Flyers",
  "Posters",
  "Banners",
  "Brochures",
  "Stickers",
  "Labels",
  "T-Shirts",
  "Hoodies",
  "Mugs",
  "Mouse Pads",
  "Magnets",
  "Calendars",
  "Letterheads",
  "Envelopes",
  "Notepads",
  "Presentation Folders",
  "Greeting Cards",
  "Postcards",
  "Invitations",
  "Wedding Cards",
  "Certificates",
  "Door Hangers",
  "Rack Cards",
  "Bookmarks",
  "Tickets",
  "Event Badges",
  "ID Cards",
  "Car Decals",
  "Window Clings",
  "Wall Art Prints",
  "Table Tents",
  "Menus",
  "Packaging Boxes",
  "Gift Wraps",
  "Paper Bags",
  "Tote Bags",
  "Lanyards",
  "Keychains",
  "Pens",
  "USB Drives",
  "Phone Cases",
  "Laptop Skins",
  "Coasters",
  "Drinkware",
  "Umbrellas",
  "Floor Decals",
  "Photo Prints",
  "Canvas Prints",
  "Yard Signs",
];

module.exports.materials = [
  "Glossy Paper",
  "Matte Paper",
  "Cardstock",
  "Vinyl",
  "Fabric",
  "Canvas",
  "Corrugated Plastic",
  "Magnetic Sheet",
  "Acrylic",
  "Aluminum",
  "Foam Board",
  "Polyester",
  "Kraft Paper",
  "Sticker Paper",
  "Leatherette",
];
