module.exports.products = [
  {
    name: "Standard Business Cards",
    category: "Business Cards",
    price: 15.99,
    description: "High-quality business cards with customizable designs.",
    stock: 100,
  },
  {
    name: "Premium Business Cards",
    category: "Business Cards",
    price: 25.99,
    description: "Glossy finish and premium material for a lasting impression.",
    stock: 80,
  },
  {
    name: "Custom Vinyl Banner",
    category: "Banners",
    price: 49.99,
    description: "Durable vinyl banners for events and promotions.",
    stock: 50,
  },
  {
    name: "Mesh Outdoor Banner",
    category: "Banners",
    price: 59.99,
    description: "Weather-resistant mesh banners, perfect for outdoor use.",
    stock: 30,
  },
  {
    name: "Custom Printed T-Shirt",
    category: "T-Shirts",
    price: 19.99,
    description: "Personalized t-shirts with high-quality printing.",
    stock: 200,
  },
  {
    name: "Bulk Printed T-Shirts (Pack of 10)",
    category: "T-Shirts",
    price: 149.99,
    description: "Order in bulk and save on custom printed t-shirts.",
    stock: 50,
  },
  {
    name: "Custom Vinyl Stickers",
    category: "Stickers",
    price: 9.99,
    description: "High-quality vinyl stickers for personal or business use.",
    stock: 300,
  },
  {
    name: "Die-Cut Stickers",
    category: "Stickers",
    price: 12.99,
    description: "Precision-cut stickers in unique shapes.",
    stock: 150,
  },
  {
    name: "A3 Custom Poster",
    category: "Posters",
    price: 14.99,
    description: "High-quality A3-sized posters with vibrant colors.",
    stock: 120,
  },
  {
    name: "Large Format Poster",
    category: "Posters",
    price: 24.99,
    description: "Great for promotions, events, or personal decoration.",
    stock: 80,
  },
];

module.exports.categories = [
  "Business Cards",
  "Banners",
  "T-Shirts",
  "Stickers",
  "Posters",
];
